name: cosap
channels:
  - conda-forge
  - bioconda
  - conda-forge/label/cf201901
  - defaults
dependencies:
  - bbmap
  - bowtie2
  - bwa
  - bwa-mem2
  - fastp
  - fastqc
  - gatk4
  - octopus==0.6.3b
  - picard
  - python
  - qualimap
  - samtools
  - somatic-sniper
  - tqdm
  - varscan
  - yaml
  - black
  - numpy
  - pillow
  - pygraphviz
  - snakefmt
  - snakemake
  - elprep
  - vardict-java
  - snpeff
  - perl-dbi
  - perl-lwp-simple
  - deepvariant
