calibrate:
  0A60:
    input: mdup_0A60.bam
    output: calibrated_0A60.bam
    table: calibration_table_0A60.table
  ACFC:
    input: mdup_ACFC.bam
    output: calibrated_ACFC.bam
    table: calibration_table_ACFC.table
creation-date: '2021-09-17 18:31:52'
final-output:
- trimmed_ACFC_1.fastq.gz
- trimmed_ACFC_2.fastq.gz
- trimmed_0A60_1.fastq.gz
- trimmed_0A60_2.fastq.gz
- unprocessed_ACFC.bam
- unprocessed_0A60.bam
- mdup_ACFC.bam
- mdup_0A60.bam
- calibrated_ACFC.bam
- calibrated_0A60.bam
- snp_ACFC_0A60.vcf
- snp_ACFC_0A60.vcf
index: {}
library_path: /home/mae/Desktop/hg38_bundle
mapping:
  0A60:
    input:
      '1': trimmed_0A60_1.fastq.gz
      '2': trimmed_0A60_2.fastq.gz
    library: bwa
    output: unprocessed_0A60.bam
    params:
      read_groups:
        ID: S13
        LB: S13
        PL: illumina
        PU: '0'
        SM: S13
  ACFC:
    input:
      '1': trimmed_ACFC_1.fastq.gz
      '2': trimmed_ACFC_2.fastq.gz
    library: bwa
    output: unprocessed_ACFC.bam
    params:
      read_groups:
        ID: Pt28N
        LB: Pt28N
        PL: illumina
        PU: '0'
        SM: Pt28N
mdup:
  0A60:
    input: unprocessed_0A60.bam
    output: mdup_0A60.bam
  ACFC:
    input: unprocessed_ACFC.bam
    output: mdup_ACFC.bam
merge: {}
sorting: {}
trim:
  0A60:
    input:
      '1': /media/mae/SeagateExpansionDrive/arif/case_1_biorep_a_wes/SRR3182433_1.fastq.gz
      '2': /media/mae/SeagateExpansionDrive/arif/case_1_biorep_a_wes/SRR3182433_2.fastq.gz
    output:
      '1': trimmed_0A60_1.fastq.gz
      '2': trimmed_0A60_2.fastq.gz
  ACFC:
    input:
      '1': /media/mae/SeagateExpansionDrive/arif/case_1_germline_wes/SRR3182423_1.fastq.gz
      '2': /media/mae/SeagateExpansionDrive/arif/case_1_germline_wes/SRR3182423_2.fastq.gz
    output:
      '1': trimmed_ACFC_1.fastq.gz
      '2': trimmed_ACFC_2.fastq.gz
variant-calling:
  ACFC_0A60_mutect:
    indel_output: indel_ACFC_0A60.vcf
    library: mutect
    normal_input: calibrated_ACFC.bam
    other_variants_output: other_variants_ACFC_0A60.vcf
    params:
      germline_sample_name: normal_sample
      tumor_sample_name: tumor_sample
    snp_output: snp_ACFC_0A60.vcf
    tumor_input: calibrated_0A60.bam
    unfiltered_variants: all_ACFC_0A60.vcf
  ACFC_0A60_varscan:
    indel_output: indel_ACFC_0A60.vcf
    library: varscan
    normal_input: calibrated_ACFC.bam
    other_variants_output: other_variants_ACFC_0A60.vcf
    params:
      germline_sample_name: normal_sample
      tumor_sample_name: tumor_sample
    snp_output: snp_ACFC_0A60.vcf
    tumor_input: calibrated_0A60.bam
    unfiltered_variants: all_ACFC_0A60.vcf
version: 0.0.1
workdir: /media/mae/SeagateExpansionDrive/arif/pipeline_reproduce/
