annotation: {}
calibrate:
  SRR3182423_1_SRR3182423_2:
    input: mdup_SRR3182423_1_SRR3182423_2.bam
    output: calibrated_SRR3182423_1_SRR3182423_2.bam
    table: calibration_table_SRR3182423_1_SRR3182423_2.table
  SRR3182433_1_SRR3182433_2:
    input: mdup_SRR3182433_1_SRR3182433_2.bam
    output: calibrated_SRR3182433_1_SRR3182433_2.bam
    table: calibration_table_SRR3182433_1_SRR3182433_2.table
creation-date: '2021-11-02 14:49:23'
index: {}
library_path: /media/bioinformaticslab/Elements/arif/hg38_bundle
mapping:
  SRR3182423_1_SRR3182423_2:
    input:
      '1': trimmed_SRR3182423_1.fastq.gz
      '2': trimmed_SRR3182423_2.fastq.gz
    library: bwa
    output: unprocessed_SRR3182423_1_SRR3182423_2.bam
    params:
      read_groups:
        ID: Pt28N
        LB: Pt28N
        PL: illumina
        PU: '0'
        SM: Pt28N
  SRR3182433_1_SRR3182433_2:
    input:
      '1': trimmed_SRR3182433_1.fastq.gz
      '2': trimmed_SRR3182433_2.fastq.gz
    library: bwa
    output: unprocessed_SRR3182433_1_SRR3182433_2.bam
    params:
      read_groups:
        ID: S13
        LB: S13
        PL: illumina
        PU: '0'
        SM: S13
mdup:
  SRR3182423_1_SRR3182423_2:
    input: unprocessed_SRR3182423_1_SRR3182423_2.bam
    output: mdup_SRR3182423_1_SRR3182423_2.bam
  SRR3182433_1_SRR3182433_2:
    input: unprocessed_SRR3182433_1_SRR3182433_2.bam
    output: mdup_SRR3182433_1_SRR3182433_2.bam
merge: {}
sorting: {}
trim:
  SRR3182423_1_SRR3182423_2:
    input:
      '1': /media/mae/SeagateExpansionDrive/arif/case_1_germline_wes/SRR3182423_1.fastq.gz
      '2': /media/mae/SeagateExpansionDrive/arif/case_1_germline_wes/SRR3182423_2.fastq.gz
    output:
      '1': trimmed_SRR3182423_1.fastq.gz
      '2': trimmed_SRR3182423_2.fastq.gz
  SRR3182433_1_SRR3182433_2:
    input:
      '1': /media/mae/SeagateExpansionDrive/arif/case_1_biorep_a_wes/SRR3182433_1.fastq.gz
      '2': /media/mae/SeagateExpansionDrive/arif/case_1_biorep_a_wes/SRR3182433_2.fastq.gz
    output:
      '1': trimmed_SRR3182433_1.fastq.gz
      '2': trimmed_SRR3182433_2.fastq.gz
variant-calling:
  mutect:
    indel_output: indel_mutect.vcf
    library: mutect
    normal_input: calibrated_SRR3182423_1_SRR3182423_2.bam
    other_variants_output: other_variants_mutect.vcf
    params:
      germline_sample_name: normal_sample
      tumor_sample_name: tumor_sample
    snp_output: snp_mutect.vcf
    tumor_input: calibrated_SRR3182433_1_SRR3182433_2.bam
    unfiltered_variants: all_mutect.vcf
  varscan:
    indel_output: indel_varscan.vcf
    library: varscan
    normal_input: calibrated_SRR3182423_1_SRR3182423_2.bam
    other_variants_output: other_variants_varscan.vcf
    params:
      germline_sample_name: normal_sample
      tumor_sample_name: tumor_sample
    snp_output: snp_varscan.vcf
    tumor_input: calibrated_SRR3182433_1_SRR3182433_2.bam
    unfiltered_variants: all_varscan.vcf
version: 0.0.1
workdir: /media/mae/SeagateExpansionDrive/arif/pipeline_reproduce/
